[package]
name = "md_latex"
version = "0.1.0"
license = "BSD-3-Clause"
edition.workspace = true
repository.workspace = true

[dependencies]
pulldown-latex = "0.7.1"
markdown-it.workspace = true

[dev-dependencies]
testing.workspace = true
rstest.workspace = true
