[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"
repository = "https://github.com/NekowebWiki/WikiMD"

[workspace.dependencies]
markdown-it = "0.6.1"
testing = { path="crates/testing" }
rstest = "0.24.0"
