[package]
name = "md_toc"
version = "0.1.0"
license = "BSD-3-Clause"
edition.workspace = true
repository.workspace = true

[dependencies]
markdown-it.workspace = true
regex.workspace = true
unbox-box = "0.1.0"

[dev-dependencies]
testing.workspace = true
rstest.workspace = true
