[package]
name = "footnote"
version = "0.1.0"
edition.workspace = true
repository.workspace = true

[dependencies]
markdown-it.workspace = true

[dev-dependencies]
testing.workspace = true
rstest.workspace = true
